// const url = 'https://rest-countries10.p.rapidapi.com/countries';
// const options = {
// 	method: 'GET',
// 	headers: {
// 		'x-rapidapi-key': 'adc1b42245msh4906e98d089216ep193730jsn2aff5af9b11c',
// 		'x-rapidapi-host': 'rest-countries10.p.rapidapi.com'
// 	}
// };

// async function flag() {
// 	const response = await fetch(url, options);
// 	const result = await response.json();
// 	// console.log(result);
// 	for (let i = 0; i < result.length; i++) {
// 		console.log(`${result[i].code.aplha2code}:"${result[i].name.shortname}",`);
// 	}

// }
// flag();

const flagImg = {
	AF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1eb.svg",
	AL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1f1.svg",
	DZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e9-1f1ff.svg",
	AS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1f8.svg",
	AD: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1e9.svg",
	AO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1f4.svg",
	AI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1ee.svg",
	AQ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1f6.svg",
	AG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1ec.svg",
	AR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1f7.svg",
	AM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1f2.svg",
	AW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1fc.svg",
	AU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1fa.svg",
	AT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1f9.svg",
	AZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1ff.svg",
	BS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1f8.svg",
	BH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1ed.svg",
	BD: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1e9.svg",
	BB: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1e7.svg",
	BY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1fe.svg",
	BE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1ea.svg",
	BZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1ff.svg",
	BJ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1ef.svg",
	BM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1f2.svg",
	AX: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1fd.svg",
	BT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1f9.svg",
	BO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1f4.svg",
	BQ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1f1.svg",
	BA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1e6.svg",
	BW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1fc.svg",
	BV: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1ef.svg",
	BR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1f7.svg",
	IO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f4.svg",
	BN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1f3.svg",
	BG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1ec.svg",
	BF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1eb.svg",
	BI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e7-1f1ee.svg",
	CV: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1fb.svg",
	KH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1ed.svg",
	CM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1f2.svg",
	CA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1e6.svg",
	KY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1fe.svg",
	CF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1eb.svg",
	TD: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1e9.svg",
	CL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1f1.svg",
	CN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1f3.svg",
	CX: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1fd.svg",
	CC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1e8.svg",
	CO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1f4.svg",
	KM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1f2.svg",
	CD: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1e9.svg",
	CG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1ec.svg",
	CK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1f0.svg",
	CR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1f7.svg",
	HR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ed-1f1f7.svg",
	CU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1fa.svg",
	CW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1fc.svg",
	CY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1fe.svg",
	CZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1ff.svg",
	CI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1ee.svg",
	DK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e9-1f1f0.svg",
	DJ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e9-1f1ef.svg",
	DM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e9-1f1f2.svg",
	DO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e9-1f1f4.svg",
	EC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ea-1f1e8.svg",
	EG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ea-1f1ec.svg",
	SV: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1fb.svg",
	GQ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1f6.svg",
	ER: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ea-1f1f7.svg",
	EE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ea-1f1ea.svg",
	SZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1ff.svg",
	ET: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ea-1f1f9.svg",
	FK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f0.svg",
	FO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f4.svg",
	FJ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1ef.svg",
	FI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1ee.svg",
	FR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	GF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	PF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1eb.svg",
	TF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1eb.svg",
	GA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1e6.svg",
	GM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1f2.svg",
	GE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1ea.svg",
	DE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e9-1f1ea.svg",
	GH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1ed.svg",
	GI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1ee.svg",
	GR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1f7.svg",
	GL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1f1.svg",
	GD: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1e9.svg",
	GP: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	GU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1fa.svg",
	GT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1f9.svg",
	GG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1ec.svg",
	GN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1f3.svg",
	GW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1fc.svg",
	GY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1fe.svg",
	HT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ed-1f1f9.svg",
	HM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ed-1f1f2.svg",
	VA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fb-1f1e6.svg",
	HN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ed-1f1f3.svg",
	HK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ed-1f1f0.svg",
	HU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ed-1f1fa.svg",
	IS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f8.svg",
	IN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f3.svg",
	ID: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1e9.svg",
	IR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f7.svg",
	IQ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f6.svg",
	IE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1ea.svg",
	IM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f2.svg",
	IL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f1.svg",
	IT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ee-1f1f9.svg",
	JM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ef-1f1f2.svg",
	JP: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ef-1f1f5.svg",
	JE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ef-1f1ea.svg",
	JO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ef-1f1f4.svg",
	KZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1ff.svg",
	KE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1ea.svg",
	KI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1ee.svg",
	KP: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1f5.svg",
	KR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1f7.svg",
	KW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1fc.svg",
	KG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1ec.svg",
	LA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1e6.svg",
	LV: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1fb.svg",
	LB: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1e7.svg",
	LS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1f8.svg",
	LR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1f7.svg",
	LY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1fe.svg",
	LI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1ee.svg",
	LT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1f9.svg",
	LU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1fa.svg",
	MO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f4.svg",
	MG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1ec.svg",
	MW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1fc.svg",
	MY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1fe.svg",
	MV: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1fb.svg",
	ML: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f1.svg",
	MT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f9.svg",
	MH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1ed.svg",
	MQ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	MR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f7.svg",
	MU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1fa.svg",
	YT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	MX: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1fd.svg",
	FM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f2.svg",
	MD: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1e9.svg",
	MC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1e8.svg",
	MN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f3.svg",
	ME: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1ea.svg",
	MS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f8.svg",
	MA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1e6.svg",
	MZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1ff.svg",
	MM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f2.svg",
	NA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1e6.svg",
	NR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1f7.svg",
	NP: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1f5.svg",
	NL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1f1.svg",
	NC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1e8.svg",
	NZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1ff.svg",
	NI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1ee.svg",
	NE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1ea.svg",
	NG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1ec.svg",
	NU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1fa.svg",
	NF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1eb.svg",
	MK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f0.svg",
	MP: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f2-1f1f5.svg",
	NO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f3-1f1f4.svg",
	OM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f4-1f1f2.svg",
	PK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1f0.svg",
	PW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1fc.svg",
	PS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1f8.svg",
	PA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1e6.svg",
	PG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1ec.svg",
	PY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1fe.svg",
	PE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1ea.svg",
	PH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1ed.svg",
	PN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1f3.svg",
	PL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1f1.svg",
	PT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1f9.svg",
	PR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f5-1f1f7.svg",
	QA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f6-1f1e6.svg",
	RO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f7-1f1f4.svg",
	RU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f7-1f1fa.svg",
	RW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f7-1f1fc.svg",
	RE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	BL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	SH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1e7.svg",
	KN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f0-1f1f3.svg",
	LC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1e8.svg",
	MF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	PM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1eb-1f1f7.svg",
	VC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fb-1f1e8.svg",
	WS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fc-1f1f8.svg",
	SM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f2.svg",
	ST: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f9.svg",
	SA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1e6.svg",
	SN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f3.svg",
	RS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f7-1f1f8.svg",
	SC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1e8.svg",
	SL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f1.svg",
	SG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1ec.svg",
	SX: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1fd.svg",
	SK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f0.svg",
	SI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1ee.svg",
	SB: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1e7.svg",
	SO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f4.svg",
	ZA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ff-1f1e6.svg",
	GS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1f8.svg",
	SS: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f8.svg",
	ES: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ea-1f1e6.svg",
	LK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f1-1f1f0.svg",
	SD: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1e9.svg",
	SR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1f7.svg",
	SJ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1ef.svg",
	SE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1ea.svg",
	CH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e8-1f1ed.svg",
	SY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f8-1f1fe.svg",
	TW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1fc.svg",
	TJ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1ef.svg",
	TZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1ff.svg",
	TH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1ed.svg",
	TL: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1f1.svg",
	TG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1ec.svg",
	TK: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1f0.svg",
	TO: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1f4.svg",
	TT: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1f9.svg",
	TN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1f3.svg",
	TM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1f2.svg",
	TC: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1e8.svg",
	TV: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1fb.svg",
	TR: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1f9-1f1f7.svg",
	UG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fa-1f1ec.svg",
	UA: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fa-1f1e6.svg",
	AE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1e6-1f1ea.svg",
	GB: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ec-1f1e7.svg",
	UM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fa-1f1f8.svg",
	US: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fa-1f1f2.svg",
	UY: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fa-1f1fe.svg",
	UZ: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fa-1f1ff.svg",
	VU: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fb-1f1fa.svg",
	VE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fb-1f1ea.svg",
	VN: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fb-1f1f3.svg",
	VG: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fb-1f1ec.svg",
	VI: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fb-1f1ee.svg",
	WF: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fc-1f1eb.svg",
	EH: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ea-1f1ed.svg",
	YE: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1fe-1f1ea.svg",
	ZM: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ff-1f1f2.svg",
	ZW: "https://rest-countries-gamma.vercel.app/emojis/svg/1f1ff-1f1fc.svg",
}

const countryName = {
	AF: "AFGHANISTAN",
	AL: "ALBANIA",
	DZ: "ALGERIA",
	AS: "AMERICAN SAMOA",
	AD: "ANDORRA",
	AO: "ANGOLA",
	AI: "ANGUILLA",
	AQ: "ANTARCTICA",
	AG: "ANTIGUA AND BARBUDA",
	AR: "ARGENTINA",
	AM: "ARMENIA",
	AW: "ARUBA",
	AU: "AUSTRALIA",
	AT: "AUSTRIA",
	AZ: "AZERBAIJAN",
	BS: "BAHAMAS",
	BH: "BAHRAIN",
	BD: "BANGLADESH",
	BB: "BARBADOS",
	BY: "BELARUS",
	BE: "BELGIUM",
	BZ: "BELIZE",
	BJ: "BENIN",
	BM: "BERMUDA",
	AX: "ÅLAND ISLANDS",
	BT: "BHUTAN",
	BO: "BOLIVIA (PLURINATIONAL STATE OF)",
	BQ: "BONAIRE, SINT EUSTATIUS AND SABA",
	BA: "BOSNIA AND HERZEGOVINA",
	BW: "BOTSWANA",
	BV: "BOUVET ISLAND",
	BR: "BRAZIL",
	IO: "BRITISH INDIAN OCEAN TERRITORY",
	BN: "BRUNEI DARUSSALAM",
	BG: "BULGARIA",
	BF: "BURKINA FASO",
	BI: "BURUNDI",
	CV: "CABO VERDE",
	KH: "CAMBODIA",
	CM: "CAMEROON",
	CA: "CANADA",
	KY: "CAYMAN ISLANDS",
	CF: "CENTRAL AFRICAN REPUBLIC",
	TD: "CHAD",
	CL: "CHILE",
	CN: "CHINA",
	CX: "CHRISTMAS ISLAND",
	CC: "COCOS (KEELING) ISLANDS",
	CO: "COLOMBIA",
	KM: "COMOROS",
	CD: "CONGO, DEMOCRATIC REPUBLIC OF THE",
	CG: "CONGO",
	CK: "COOK ISLANDS",
	CR: "COSTA RICA",
	HR: "CROATIA",
	CU: "CUBA",
	CW: "CURAÇAO",
	CY: "CYPRUS",
	CZ: "CZECHIA",
	CI: "CÔTE D'IVOIRE",
	DK: "DENMARK",
	DJ: "DJIBOUTI",
	DM: "DOMINICA",
	DO: "DOMINICAN REPUBLIC",
	EC: "ECUADOR",
	EG: "EGYPT",
	SV: "EL SALVADOR",
	GQ: "EQUATORIAL GUINEA",
	ER: "ERITREA",
	EE: "ESTONIA",
	SZ: "ESWATINI",
	ET: "ETHIOPIA",
	FK: "FALKLAND ISLANDS (MALVINAS)",
	FO: "FAROE ISLANDS",
	FJ: "FIJI",
	FI: "FINLAND",
	FR: "FRANCE",
	GF: "FRENCH GUIANA",
	PF: "FRENCH POLYNESIA",
	TF: "FRENCH SOUTHERN TERRITORIES",
	GA: "GABON",
	GM: "GAMBIA",
	GE: "GEORGIA",
	DE: "GERMANY",
	GH: "GHANA",
	GI: "GIBRALTAR",
	GR: "GREECE",
	GL: "GREENLAND",
	GD: "GRENADA",
	GP: "GUADELOUPE",
	GU: "GUAM",
	GT: "GUATEMALA",
	GG: "GUERNSEY",
	GN: "GUINEA",
	GW: "GUINEA-BISSAU",
	GY: "GUYANA",
	HT: "HAITI",
	HM: "HEARD ISLAND AND MCDONALD ISLANDS",
	VA: "HOLY SEE",
	HN: "HONDURAS",
	HK: "HONG KONG",
	HU: "HUNGARY",
	IS: "ICELAND",
	IN: "INDIA",
	ID: "INDONESIA",
	IR: "IRAN (ISLAMIC REPUBLIC OF)",
	IQ: "IRAQ",
	IE: "IRELAND",
	IM: "ISLE OF MAN",
	IL: "ISRAEL",
	IT: "ITALY",
	JM: "JAMAICA",
	JP: "JAPAN",
	JE: "JERSEY",
	JO: "JORDAN",
	KZ: "KAZAKHSTAN",
	KE: "KENYA",
	KI: "KIRIBATI",
	KP: "KOREA (DEMOCRATIC PEOPLE'S REPUBLIC OF)",
	KR: "KOREA, REPUBLIC OF",
	KW: "KUWAIT",
	KG: "KYRGYZSTAN",
	LA: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
	LV: "LATVIA",
	LB: "LEBANON",
	LS: "LESOTHO",
	LR: "LIBERIA",
	LY: "LIBYA",
	LI: "LIECHTENSTEIN",
	LT: "LITHUANIA",
	LU: "LUXEMBOURG",
	MO: "MACAO",
	MG: "MADAGASCAR",
	MW: "MALAWI",
	MY: "MALAYSIA",
	MV: "MALDIVES",
	ML: "MALI",
	MT: "MALTA",
	MH: "MARSHALL ISLANDS",
	MQ: "MARTINIQUE",
	MR: "MAURITANIA",
	MU: "MAURITIUS",
	YT: "MAYOTTE",
	MX: "MEXICO",
	FM: "MICRONESIA (FEDERATED STATES OF)",
	MD: "MOLDOVA, REPUBLIC OF",
	MC: "MONACO",
	MN: "MONGOLIA",
	ME: "MONTENEGRO",
	MS: "MONTSERRAT",
	MA: "MOROCCO",
	MZ: "MOZAMBIQUE",
	MM: "MYANMAR",
	NA: "NAMIBIA",
	NR: "NAURU",
	NP: "NEPAL",
	NL: "NETHERLANDS, KINGDOM OF THE",
	NC: "NEW CALEDONIA",
	NZ: "NEW ZEALAND",
	NI: "NICARAGUA",
	NE: "NIGER",
	NG: "NIGERIA",
	NU: "NIUE",
	NF: "NORFOLK ISLAND",
	MK: "NORTH MACEDONIA",
	MP: "NORTHERN MARIANA ISLANDS",
	NO: "NORWAY",
	OM: "OMAN",
	PK: "PAKISTAN",
	PW: "PALAU",
	PS: "PALESTINE, STATE OF",
	PA: "PANAMA",
	PG: "PAPUA NEW GUINEA",
	PY: "PARAGUAY",
	PE: "PERU",
	PH: "PHILIPPINES",
	PN: "PITCAIRN",
	PL: "POLAND",
	PT: "PORTUGAL",
	PR: "PUERTO RICO",
	QA: "QATAR",
	RO: "ROMANIA",
	RU: "RUSSIAN FEDERATION",
	RW: "RWANDA",
	RE: "RÉUNION",
	BL: "SAINT BARTHÉLEMY",
	SH: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
	KN: "SAINT KITTS AND NEVIS",
	LC: "SAINT LUCIA",
	MF: "SAINT MARTIN (FRENCH PART)",
	PM: "SAINT PIERRE AND MIQUELON",
	VC: "SAINT VINCENT AND THE GRENADINES",
	WS: "SAMOA",
	SM: "SAN MARINO",
	ST: "SAO TOME AND PRINCIPE",
	SA: "SAUDI ARABIA",
	SN: "SENEGAL",
	RS: "SERBIA",
	SC: "SEYCHELLES",
	SL: "SIERRA LEONE",
	SG: "SINGAPORE",
	SX: "SINT MAARTEN (DUTCH PART)",
	SK: "SLOVAKIA",
	SI: "SLOVENIA",
	SB: "SOLOMON ISLANDS",
	SO: "SOMALIA",
	ZA: "SOUTH AFRICA",
	GS: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
	SS: "SOUTH SUDAN",
	ES: "SPAIN",
	LK: "SRI LANKA",
	SD: "SUDAN",
	SR: "SURINAME",
	SJ: "SVALBARD AND JAN MAYEN",
	SE: "SWEDEN",
	CH: "SWITZERLAND",
	SY: "SYRIAN ARAB REPUBLIC",
	TW: "TAIWAN, PROVINCE OF CHINA",
	TJ: "TAJIKISTAN",
	TZ: "TANZANIA, UNITED REPUBLIC OF",
	TH: "THAILAND",
	TL: "TIMOR-LESTE",
	TG: "TOGO",
	TK: "TOKELAU",
	TO: "TONGA",
	TT: "TRINIDAD AND TOBAGO",
	TN: "TUNISIA",
	TM: "TURKMENISTAN",
	TC: "TURKS AND CAICOS ISLANDS",
	TV: "TUVALU",
	TR: "TÜRKİYE",
	UG: "UGANDA",
	UA: "UKRAINE",
	AE: "UNITED ARAB EMIRATES",
	GB: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
	UM: "UNITED STATES MINOR OUTLYING ISLANDS",
	US: "UNITED STATES OF AMERICA",
	UY: "URUGUAY",
	UZ: "UZBEKISTAN",
	VU: "VANUATU",
	VE: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
	VN: "VIET NAM",
	VG: "VIRGIN ISLANDS (BRITISH)",
	VI: "VIRGIN ISLANDS (U.S.)",
	WF: "WALLIS AND FUTUNA",
	EH: "WESTERN SAHARA *",
	YE: "YEMEN",
	ZM: "ZAMBIA",
	ZW: "ZIMBABWE",
}

// country List with their currency code
const countryList = {
	AE: "AED",
	AF: "AFN",
	AG: "XCD",
	AL: "ALL",
	AM: "AMD",
	AN: "ANG",
	AO: "AOA",
	AQ: "AQD",
	AR: "ARS",
	AU: "AUD",
	AZ: "AZN",
	BA: "BAM",
	BB: "BBD",
	BD: "BDT",
	BE: "XOF",
	BG: "BGN",
	BH: "BHD",
	BI: "BIF",
	BM: "BMD",
	BN: "BND",
	BO: "BOB",
	BR: "BRL",
	BS: "BSD",
	BV: "NOK",
	BW: "BWP",
	BY: "BYR",
	BZ: "BZD",
	CA: "CAD",
	CD: "CDF",
	CF: "XAF",
	CH: "CHF",
	CL: "CLP",
	CN: "CNY",
	CO: "COP",
	CR: "CRC",
	CU: "CUP",
	CV: "CVE",
	CY: "CYP",
	CZ: "CZK",
	DJ: "DJF",
	DK: "DKK",
	DO: "DOP",
	DZ: "DZD",
	EC: "ECS",
	EE: "EEK",
	EG: "EGP",
	ET: "ETB",
	FR: "EUR",
	FJ: "FJD",
	FK: "FKP",
	GB: "GBP",
	GE: "GEL",
	GG: "GGP",
	GH: "GHS",
	GI: "GIP",
	GM: "GMD",
	GN: "GNF",
	GT: "GTQ",
	GY: "GYD",
	HK: "HKD",
	HN: "HNL",
	HR: "HRK",
	HT: "HTG",
	HU: "HUF",
	ID: "IDR",
	IL: "ILS",
	IN: "INR",
	IQ: "IQD",
	IR: "IRR",
	IS: "ISK",
	JM: "JMD",
	JO: "JOD",
	JP: "JPY",
	KE: "KES",
	KG: "KGS",
	KH: "KHR",
	KM: "KMF",
	KP: "KPW",
	KR: "KRW",
	KW: "KWD",
	KY: "KYD",
	KZ: "KZT",
	LA: "LAK",
	LB: "LBP",
	LK: "LKR",
	LR: "LRD",
	LS: "LSL",
	LT: "LTL",
	LV: "LVL",
	LY: "LYD",
	MA: "MAD",
	MD: "MDL",
	MG: "MGA",
	MK: "MKD",
	MM: "MMK",
	MN: "MNT",
	MO: "MOP",
	MR: "MRO",
	MT: "MTL",
	MU: "MUR",
	MV: "MVR",
	MW: "MWK",
	MX: "MXN",
	MY: "MYR",
	MZ: "MZN",
	NA: "NAD",
	NC: "XPF",
	NG: "NGN",
	NI: "NIO",
	NP: "NPR",
	NZ: "NZD",
	OM: "OMR",
	PA: "PAB",
	PE: "PEN",
	PG: "PGK",
	PH: "PHP",
	PK: "PKR",
	PL: "PLN",
	PY: "PYG",
	QA: "QAR",
	RO: "RON",
	RS: "RSD",
	RU: "RUB",
	RW: "RWF",
	SA: "SAR",
	SB: "SBD",
	SC: "SCR",
	SD: "SDG",
	SE: "SEK",
	SG: "SGD",
	SK: "SKK",
	SL: "SLL",
	SO: "SOS",
	SR: "SRD",
	ST: "STD",
	SV: "SVC",
	SY: "SYP",
	SZ: "SZL",
	TH: "THB",
	TJ: "TJS",
	TM: "TMT",
	TN: "TND",
	TO: "TOP",
	TR: "TRY",
	TT: "TTD",
	TW: "TWD",
	TZ: "TZS",
	UA: "UAH",
	UG: "UGX",
	US: "USD",
	UY: "UYU",
	UZ: "UZS",
	VE: "VEF",
	VN: "VND",
	VU: "VUV",
	YE: "YER",
	ZA: "ZAR",
	ZM: "ZMK",
	ZW: "ZWD",
  };
  